### ISSUE TITLE
No firmware.hex to download

### ISSUE THREAD

**Issue by ocarvallo** [henols/firestarter#7]
In both win 10 and linux got the following. I gather from issue 1 above you may be reworking the fware to fix it, thus the file will not be available till corrected.

oc@oswaldo-hpenvypro4b000ultrabookpc:~/.local/bin$ python3 firestarter fw -i
ERROR - Timeout
No programmer found
Trying to install firmware version: 1.0.10
Found programmer at port: /dev/ttyACM0
Downloading firmware...
Traceback (most recent call last):
  File "firestarter", line 8, in <module>
    sys.exit(main())
  File "/home/oc/.local/lib/python3.8/site-packages/firestarter/main.py", line 726, in main
    firmware(args.install, args.avrdude_path, args.port)
  File "/home/oc/.local/lib/python3.8/site-packages/firestarter/main.py", line 250, in firmware
    install_firmware(url, avrdude_path, selected_port)
  File "/home/oc/.local/lib/python3.8/site-packages/firestarter/main.py", line 327, in install_firmware
    with open(firmware_path, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/oc/.firestarter/firmware.hex'

**Comment by henols** [comment]
What's in the _/home/oc/.firestarter/_ folder?

**Comment by ocarvallo** [comment]
There is no such folder...it is like firestarter should have created it and put firmware.hex file in it...but no.
I could have tried to use avrdude to program the arduino but I do not see a firmware.hex file in the rep.

**Comment by henols** [comment]
Update the python app and try again to install the FW.

**Comment by ocarvallo** [comment]
Fantastic...upgraded to firestarter subv 13...connct to arduino:
oc@oswaldo-hpenvypro4b000ultrabookpc:~/.local/bin$ python3 firestarter fw -i 
ERROR - Timeout
No programmer found
Trying to install firmware version: 1.0.11
Found programmer at port: /dev/ttyACM0
Downloading firmware...
Firmware downloaded
Installing firmware
Firmware updated
oc@oswaldo-hpenvypro4b000ultrabookpc:~/.local/bin$ python3 firestarter fw
Reading version
Firmware version: 1.0.11
You have the latest version
oc@oswaldo-hpenvypro4b000ultrabookpc:~/.local/bin$ python3 firestarter vcc
Reading VCC voltage
VCC Voltage: 4.82v

Great....thanks!!

**Comment by ocarvallo** [comment]
FYI I had to replace the avrdude.conf file in the python package with the one that the avrdude install stored in /etc...I noticed that the file headers were different and perhaps that was bothering the download ....see below:

oc@oswaldo-hpenvypro4b000ultrabookpc:~/.local/bin$ python3 firestarter fw -i 
ERROR - Timeout
No programmer found
Trying to install firmware version: 1.0.11
Error connecting to programmer at port: /dev/ttyACM0
avrdude: error at /home/oc/.local/lib/python3.8/site-packages/firestarter/data/avrdude.conf:402: syntax error
avrdude: error reading system wide configuration file "/home/oc/.local/lib/python3.8/site-packages/firestarter/data/avrdude.conf"

....just in case that someody as a similar issue!!

**Comment by ocarvallo** [comment]
Hi Henrik, many thanks for your work on Firestarter, it is a really cool
app for Andreas programmer.

FYI, I had some issues with the app in Win 10 at the beginning (it failed
to find the programmer) but then after doing a fw command with --port COM5
(as checked in Dev Mgr) it worked fine and it remembered the location for
all other instructions.

Thanks and best regards, Oswaldo
